<!DOCTYPE html>
<html lang="en">
    <head>
        <title>SR Standard</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="style.css" rel="stylesheet">
        <script src="./dist/bundle.js"></script>
    </head>

    <header>

    </header>

    <body>
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="banner-container">
                        <div class="banner-header">
                            Skyrocket Standard Boilerplate
                        </div>
                        <div class="banner-content">
                            <p>
                                Time to start your own project with Skyrocket Standard Boilerplate.
                            </p>
                            <p>
                                Following a standard SASS design and file structure makes it easier for the team to co-work on the front end side of the project. SR Standard Boilperplate also uses webpack that is already configured just run <strong>"npm install"</strong> and wait till the packages are installed, then run <strong>"npm run build"</strong> a script that is included on the package.json file that automates the deletion of autogenerated files (bundle and style) so it cleans the old code and triggers the watch command for webpack.
                            </p>
                        </div>
                    <div>
                </div>
            </div>
        </div>
    </body>

    <footer>

    </footer>
</html>